version: '3.8'

services:
  nodejs:
    image: node:latest
    container_name: my_nodejs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tty: true

  mongodb:
    image: mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: my_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j
    container_name: my_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"

  cassandra-1:
    image: "cassandra:3.11.9"
    container_name: "cassandra-1"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
 
  cassandra-2:
    image: "cassandra:3.11.9"
    container_name: "cassandra-2"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-1"
 
  cassandra-3:
    image: "cassandra:3.11.9"
    container_name: "cassandra-3"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-2"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: my_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: my_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge

volumes:
  mongodb_data:
